### ISSUE TITLE
Add option to remove the menu-bar

### ISSUE THREAD

**Issue by terlar** [rhysd/electron-open-url#1]
It would be nice if the CLI had an option to disable the menu bar by default, right now I have to run `F11` to toggle full screen mode.

So something like `--fullscreen` or if it is possible to get rid of the toolbar in some other way.

**Comment by rhysd** [comment]
Which platform (macOS, Linux or Windows) are you using? Menu bar behavior depends on platform.

**Comment by terlar** [comment]
I am using Arch Linux with xmonad as window manager. So currently it shows a menu bar if not switching to full screen mode. Full screen mode might have some other side-effects, but for a tiling window manager it does not. Anyways it is still useful with an option for `fullscreen`. If you just want to disable the menu, then there are other approaches, I tried `win.setMenu(null);` and it disabled the menu, not sure how it will behave in MacOS though.

**Comment by rhysd** [comment]
There are two menu bar in Electron app. `win.setMenu` and `Menu.setApplicationMenu`. So, even if setting it to `null`, macOS's menubar does not disapear. But I think disabling menu by default is not so good behavior because we can many things via menu bar.

So, if you want to implement this, would you follow below?

1. add `--disable-menu` option
2. if the option specified, call `setMenu(null)`
3. please do not call `Menu.setApplicationMenu(null)` because disabling menu on macOS does not have any benefits.

**Comment by terlar** [comment]
I agree that having the menu bar disabled by default is a bad thing. Thank you for the pointers, I will add a `--disable-menu` option and make a PR.

**Comment by rhysd** [comment]
I published v1.5.0. Thank you for contribution.
